name: deploy-py-lambda

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses:  kuri-megane/py-lambda-action@master
      with:
        lambda_layer_arn: 'arn:aws:lambda:ap-northeast-1:249908578461:layer:AWSLambda-Python38-SciPy1x'
        lambda_function_name: 'arn:aws:lambda:ap-northeast-1:152716024687:function:test'
        lambda_region: 'ap-northeast-1'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Notify result to slack
        uses: kuri-megane/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Deploy Lambda*'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}